---
title: 'Welcome to Minicourse #15'
author: "Teaching Statistics with R and RStudio"
date: "January, 2016"
output: 
  ioslides_presentation:
    widescreen: true
  
---

## Welcome to Minicourse 15

### **Minicourse Web Page**

  * [http://mosaic-web.org/from-meetings-workshops/jmm-2016-mini-course/](http://mosaic-web.org/from-meetings-workshops/jmm-2016-mini-course/)

### **While we are waiting...**

  * **Introduce yourself** to your neighbor(s).
 
    

  * **Try out the FREE INTERNET** and login to the RStudio server
     -- [rstudio.calvin.edu](rstudio.calvin.edu) --
     I have a username and password for you.
     
    * Sheraton-Seattle-Meeting-Room
    * METROA3



## Outline of Day 1

  1. Introductions
  
  2. RStudio Quick start
 
  3. Less Volume, More Creativity 
 
    * Getting started with the mosaic package
    * An approach that can be used in other contexts as well
   
  4. Creating documents with R Markdown (if time)
 
## Other SIGMAA Stat Ed Stuff...

### **Contributed Paper Sessions** -- *Yakima 1*

  * 2:15 - 5:55 Wed -- Intro Stats
  * 1:00 - 4:15 Thur -- Intro Stats
  * 1:00 - 2:35 Fri -- Other Stats
    
### **Panel Discussion on Guidelines for Stat Ed** -- *Room 609*

 * 8:00 - 9:20 Fri
    
### **Business Meeting** (Thur, 5:30, 6:00, 6:50) -- *Yakima 1*

  * reception, awards, business meeting, door prizes
  * Tim Hesterberg (Google) will present on 
  "Big data, experiments, and resampling at Google"

## Introductions

  * **Randy Pruim**, Calvin College
  
  * **Robin Lock**, St Lawrence University
  
  * **Katie Kinnaird**, Maclester College
  
  * **Tim Hesterberg**, Google
  
  * **Danny Kaplan**, Macalester College
  
  * **Nick Horton**, Amherst College
  
  