---
title: "JMM 2015 Minicourse"
author: "R Pruim and N Horton"
date: "January 7, 2015"
output: html_document
---


# Schedule for JMM 2015 Minicourse

## Saturday Morning

### Welcome, Introduction [Randy/Nick]
  
  * Brief Intro of Workshop leaders
    
  * Goals:  What we will/won't be doing
    * Perhaps a slide or two
      
  * Get to know your neighbor activity
      * Don't want to lose too much time here
      
  * Other Stat Ed things at JMM
    * a couple slides pitching sessions, business meeting, Hadley's talk
      
    
      
### Introduction to RStudio [Nick]
  * Make sure everyone has a working version of RStudio with mosaic
    * Usernames and passwords for server
    * sanity check on local installs
  * Basic orientation to RStudio
    * Calculator and other simple R computations
    * Load a data set?  [Seems like people always want to know this]
    * Load packages?
      * I could have what we need set to pre-load or we could show people how to do it
      
### Less Volume, More Creativity [Randy]
  
### Assignment

  * Need to come up with a good idea for this.

## Monday Morning

### Warm-up
  * 
### Using RMarkdown [Nick]
  * 
  
### Resampling and Bootstrap
  * Hypothesis testing
     * Lady Tasting Tea [Randy]
     * Other examples?
     
  * Confidence Intervals
    * Examples?
    
  * Pointer to Tim Hesterberg's paper

### Mention what is in the Compendium
    

